# docker-compose.yaml
version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
     - DATABASE_URL=mysql://username:password@db:3306/db_test_meetwatshing?serverVersion=5.7&charset=utf8mb4
    depends_on:
      - db
    networks:
      - backend

  web:
    image: nginx:1.27.0
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db_test_meetwatshing
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - /etc/mysql/my.cnf
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
